# Generated by Django 4.1.5 on 2023-06-16 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_liking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liking',
        ),
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
